faithapp/faith1/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('index/', home,name='index'),
    path('contact/',contact, name='contact'),
    path('about/',about, name='about'),
    path('login/', login, name='login'),
    path('navigation/', navigation, name = 'navigation'),
    path('base/', base, name = 'base'),
    path('new_products/', new_products, name='new_products'),
    path('new_orders/', new_orders, name='new_orders'),
    path('new_customers/', new_customers, name='new_customers'),
    path('new_suppliers/', new_suppliers, name='new_suppliers'),
    path('category/', category, name='category'),
    path('orders/', orders, name='orders'),
    path('products/', products, name='products'),
    path('suppliers/', suppliers, name='suppliers'),
]

faithapp/faithapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('faith1.urls')),
]

faithapp/faith1/models.py
from django.db import models

# Create your models here.
class Customers(models.Model):
    first_name = models.CharField(max_length=100) 
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
   
    def __str__(self) -> str:
        return self.first_name + self.last_name

class Suppliers(models.Model):
    products = models.ForeignKey("Products", on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=50)
    postal_code = models.IntegerField()
    contact_number = models.CharField(max_length=20)
    contact_title = models.CharField(max_length=20)
    items = models.CharField(max_length=10)
    home_page = models.CharField(max_length=10)
    company_name = models.CharField(max_length=10)
    country = models.CharField(max_length=10)
    county = models.CharField(max_length=10)
    

    def __str__(self) -> str:
        return self.name

class Products(models.Model):
    product_type = models.CharField(max_length=8)
    product_name = models.CharField(max_length=8)
    quantity_per_unit = models.IntegerField()
    unit_price = models.DecimalField(max_digits=8,decimal_places=2)
    unit_in_stock = models.IntegerField()
    unit_order = models.IntegerField()
    re_order_level = models.IntegerField()
 
    def __str__(self) -> str:
        return self.product_name

class Orders(models.Model):
    customers = models.ForeignKey("Customers", on_delete=models.CASCADE)
    products = models.ForeignKey("Products", on_delete=models.CASCADE)
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    order_type = models.CharField(max_length=10)
    order_quantity = models.IntegerField()
    name = models.CharField(max_length=7)
    order_price = models.DecimalField(max_digits=8,decimal_places=2)
    order_discount = models.IntegerField()
     
    def __str__(self) -> str:
        return self.order_name

class category(models.Model):
    category_name = models.CharField(max_length=10)
    description = models.CharField(max_length=50)
     
    def __str__(self) -> str:
        return self.category_name

faithapp/faith1/views.py
from django.shortcuts import render
from django.db import IntegrityError

# Create your views here.
def home(request):
    return render(request,'index.html')

def contact(request):
    return render(request,'contact.html')

def about(request):
    return render(request,'about.html')
# To authenticate user
def login (request):
    return render(request, 'login.html')

def navigation (request):
    return render (request, 'navigation.html')

def base (request):
    return render (request, 'base.html')

def orders (request):
    return render (request, 'orders.html')

def products (request):
    return render (request, 'products.html')

def suppliers (request):
    return render (request, 'suppliers.html')

def category(request):
    if request.method== 'POST':
        category_name = request.POST['category_name']
        description = request.POST['description']
        try:
            category.objects.create(
                category_name = category_name,
                description = description
        )
            return render (request, 'category.html')
    
        except IntegrityError: 
            error ="Duplicate product information"
        except  Exception as e:
            error = str(e) 
        
        context={"error":error}
        return render(request, 'category.html',context)
    
def new_products(request):
    if request.method=='POST':
        product_type = request.POST['product_type']
        product_name = request.POST['product_name']
        quantity_per_unit = request.POST['quantity_per_unit']
        unit_price = request.POST['unit_price']
        unit_in_stock = request.POST['unit_in_stock']
        unit_order = request.POST['unit_order']
        re_order_level = request.POST['re_order_level']
       
        try:
            Products.objects.create(
                product_type = product_type,
                product_name = product_name,
                quantity_per_unit= quantity_per_unit,
                unit_price = unit_price,
                unit_in_stock = unit_in_stock,
                unit_order = unit_order,
                re_order_level = re_order_level

        )
           

        except IntegrityError: 
            error ="Duplicate product information"
        except  Exception as e:
            error = str(e) 
            
        context = {"error":error}
        return render(request, 'new_products.html', context)
    
    return render (request, 'new_products.html')

def new_orders (request):
    if request.method=='POST':
        customers = request.POST[f"{Customers.first_name}"]
        products = request.POST[f"{Products.product_name}"]
        category = request.POST[f"{Category.category_name}"]
        order_type = request.POST['order_type']
        order_quantity =request.POST['order_quantity']
        name = request.POST['name']
        order_price = request.POST['order_price']
        order_discount = request.POST['order_discount']

        try:
            Orders.objects.create(
                order_type = order_type,
                order_quantity = order_quantity,
                oder_name = order_quantity,
                order_price=order_price,
                order_discount = order_discount
        )
           
        
        except IntegrityError: 
            error ="Duplicate product information"
        except  Exception as e:
            error = str(e) 
        
        context = {"error":error}
        return render (request,'new_orders.html',context)
   
    return render (request,'new_orders.html')
    
def new_customers (request):
    if request.method== 'POST':
        first_name = request.POST['first_name'] 
        last_name = request.POST['last_name']
        phone_number = request.POST['phone_number']

        try:
            Customers.objects.create( 
                first_name = first_name,
                last_name = last_name,
                phone_number = phone_number 
                )
        
           
        except IntegrityError: 
                error ="Duplicate product information"
        except  Exception as e:
            error = str(e) 
        context={"error": error}  
        return render (request, 'new_customers.html', context)

    return render (request, 'new_customers.html')

def new_suppliers (request):
    if request.method== 'POST':
         name = request.POST['name']
         address =request.POST['address']
         postal_code = request.POST['postal_code']
         contact_number = request.POST['contact_number']
         contact_title = request.POST['contact_title']
         items = request.POST['items']
         home_page = request.POST['home_page']
         company_name = request.POST['company_name']
         country = request.POST['country']
         county = request.POST['county']
          
         try:
            Suppliers.objects.create(
                name = name,
                address = address,
                postal_code = postal_code,
                contact_number =  contact_number,
                contact_title = contact_title,
                items = items,
                home_page = home_page,
                company_name = company_name,
                country = country,
                county =county
            )
         
    
         except IntegrityError: 
            error ="Duplicate product information"
         except  Exception as e:
          error = str(e) 
    
         context={"error": error}
         return render (request,'new_suppliers.html', context)

    return render (request, 'new_suppliers.html')
    

faithapp/faith1/templates/about.html
<!DOCTYPE html>
<a href="{% url 'index' %}">Home</a>
<html>
    <head>
        <h1 style="background-color: rgb(221, 231, 231);">About Us</h1>
    </head>
    <body style="background-color: rgb(190, 197, 195);">
            
            <P>
Kirinyaga Distributors Ltd is a principal supplier of tried, tested and trusted brands in animal health and crop 
farming sectors, all developed with the key objectives of increasing production and productivity on the 
farms. The quality of Our Brands that make up the range of high quality products and solutions offering by
Kirinyaga Distributors Ltd is unparalleled in the region.
Through our exclusive countrywide distributor system, a strong regional presence in Tanzania, Uganda, 
Burundi and Rwanda, we ensure our products are readily available throughout the greater East Africa region conveniently 
and cost-efficiently.
            </P>
    </body>
</html>

faithapp/faith1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <linl rel="stylesheet" href="styles.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    body{
      background-color: skyblue; 
    }
  </style>
<title>Distributors</title>
</head>
<body id="mystyles">
    {% block content %}

    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

</body>

</html>

faithapp/faith1/templates/category.html
{% include 'base.html'%}
{% include 'navigation.html'%}
{% load static %}
{% block content %}
<div class="container-fluid" >
    <div class="col-lg-12">
        <form id="category">
            <div class="row form-group">
            
                    <h3>Categories</h3>
                
                <div class="col-md-4">
                    <label for="category-name">Category Name</label>
                    <input type="text" class="form-control" name="">    
                </div>
            
            <div class="row form">
                <div class="col-md-4">
                    <label for="description">Description</label>
                    <input type="text" class="form-control" name=""> 
                </div>
            </div>
            <input type="submit" value="submit" class="form-control" name=""  
            >
        </div>
        </form>
    </div>
</div>
</div>
{% endblock content %}

faithapp/faith1/templates/contact.html
{% include 'base.html'%}
{% include 'navigation.html'%}
{% block content %}

<div class="container text-center">
    <div class="row">
      <div class="col">
        <h6><i class="fa-solid fa-phone"></i> Telephone</h6>
        <p> <a href="Tel:+254740783614">+254 740 783 614</a></p>
      </div>
      <div class="col">
        <h6><i class="fa-solid fa-envelope"></i> Email</h6>
        <p> <a href="mailto:faithmwangi2001@gmail.com">faithmwangi2000@gmail.com</a></p>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <h6><i class="fa-solid fa-fax"></i> Fax</h6>
        <p> <a href="fax:12345"> +254 20 286 0000</a></p>
      </div>
      <div class="col">
        <h6><i class="fa-solid fa-location-dot"></i> Physical Location</h6>
        <p> <a href="maps.google.com/maps?=kirinyaga"> Kerugoya Town</a></p>

      </div>
      <div class="col">
        <h6><i class="fa-brands fa-usps"></i> Postal address</h6>
        <p>P.O Box 91 - 10300, Kerugoya</p>
      </div>
    </div>
  </div>
  {% endblock content %}

faithapp/faith1/templates/index.html
{% include 'base.html'%}
{% include 'navigation.html'%}
{% load static %}
{% block content %}

<h1 style="text-align: center;"><b>Welcome to Kirinyaga Distributors</b></h1>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ;">
<!-- Carousel -->
<div id="demo" class="carousel slide" data-bs-ride="carousel">

    <!-- Indicators/dots -->
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
      <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
      <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
      <button type="button" data-bs-target="#demo" data-bs-slide-to="3"></button>
    </div>
    
    <!-- The slideshow/carousel -->
    <div class="carousel-inner" style="margin-left: 150px; margin-right: 150px; height: 600px;">
      <div class="carousel-item active">
        <img src="{% static 'images/Image1.jpg' %}" alt="Los Angeles" class="d-block" style="width:80%" height="400px">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/Image2.jpg' %}" alt="Chicago" class="d-block" style="width:80%" height="400px">
      </div>
      <div class="carousel-item">
        <img src="{%static 'images/image3.jpg' %}" alt="New York" class="d-block" style="width:80%" height="400px">
      </div>
      <div class="carousel-item">
        <img src="{%static 'images/image4.jpg' %}" alt="Nairobi" class="d-block" style="width:80%" height="400px">
      </div>
    </div>
    
    <!-- Left and right controls/icons -->
    <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
      <span class="carousel-control-next-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
      <span class="carousel-control-next-icon"></span>
    </button>
  </div>
<p>
  
 Once menu planning is completed, the Ordering / Purchasing control point is the next logical step to be
     addressed. In fact, the menu determines the ingredients to be purchased, the variety of products 
     needed, and the relative amounts. One of the major objectives of Ordering / Purchasing is to obtain 
     the right quality and quantity of items at the right price from the right supplier. The goals are to 
     maintain quality and value, strengthen the establishment's competitive position, and minimize the 
     investment in inventory.

More than any other basic operating activity, Ordering / Purchasing relates to cost and quality controls.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 In fact, most food service businesses spend 30-50% of their total sales revenue on product Ordering /             
  Purchasing. Therefore, cost avoidance in Ordering / Purchasing has the potential to translate directly             
   to the operation's bottom line.</p><p> Conversely, the failure to properly control food costs can have a more         
   devastating effect than overspending in most other cost categories. It is not surprising that the           
    primary concern of many operators is their food cost. As costs increase, this concern grows. Rising          
    food costs often force management to reexamine the operation's Ordering / Purchasing needs.                              
</p>              

<div class="card-group">
  <div class="card">
    <img src="{% static 'images/suppliers.jpg' %}" class="card-img-top" alt="..." style="height: 200px;">
    <div class="card-body">
      <h5 class="card-title">Suppliers</h5>
      <p class="card-text">It is important to choose the suppliers wisely because when the times get tough they are the 
        ones that will help you and your company the most. Give this sentence a thought now that we are in the specific
         market situation.</p>
    </div>
    <a href="#" class="btn btn-primary"style="margin-left: 150px;margin-right: 150px;;">See More</a>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img src="{% static 'images/products.jpg' %}" class="card-img-top" alt="..."style="height: 200px;">
    <div class="card-body">
      <h5 class="card-title">Products</h5>
      <p class="card-text">Products are simply objects that are manufactured, stored, transported, advertised, and then 
        sold. While products can either be tangible or intangible, services are intangible. The differences between 
        products and services are based on different factors, including tangibility, perishability, variability, and 
        heterogeneity.</p>
    </div>
    <a href="#" class="btn btn-primary"style="margin-left: 150px;margin-right: 150px;">See More</a>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img src="{% static 'images/customers.jpg' %}" class="card-img-top" alt="..." style="height: 200px;">
    <div class="card-body">
      <h5 class="card-title">Customers</h5>
      <p class="card-text">All businesses compete with other companies to attract customers either by aggressively 
        advertising their products, lowering prices to expand their customer bases, or developing unique products and 
        experiences that customers love. </p>
    </div>
    <a href="#" class="btn btn-primary" style="margin-left: 150px;margin-right: 150px;">See More</a>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>
{% endblock content %}

faithapp/faith1/templates/navigation.html
<div class="text-end">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Kirinyaga Distributors</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="text-end" id="navbarNavDropdown">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Resources
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Suppliers</a></li>
            <li><a class="dropdown-item" href="#">Products</a></li>
            <li><a class="dropdown-item" href="#">Customers</a></li>
            <li><a class="dropdown-item" href="#">Orders</a></li>

          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</div>

faithapp/faith1/templates/new_customers.html
{% load static %}
{% include 'base.html'%}
{% include 'navigation.html'%}
{% block content %}

<div class="container_fluid" >
    <div class="col-lg-12">
        <form id="customer">
            <div class="row form-group" >
                <div>
                    <h3>Customers</h3>
                </div>
                <div class="row form">
                    <div class="col-md-4">
                        
                        <label for="first-name">First Name:</label>
                        <input type="text" class="form-control" name="name">
                        <label for="last-name">Last Name:</label>
                        <input type="text" class="form-control" name="name">
                    </div>
                </div>
                <div class="row form">
                    <div class="col-md-4">
                        <label for="phone-number">Phone Number:</label>
                        <input type="number" class="form-control" name="">
                    </div>
                </div>
                <div class="row form">
                    <div class="col-md-4">
                        <label for="age">Age:</label>
                        <input type="number" class="form-control" name="">
                    </div>
                </div>
                <div class="row form">
                    <div class="col-md-4">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

faithapp/faith1/templates/new_orders.html
{% include 'base.html'%}
{% include 'navigation.html'%}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="col-lg-12">
        <form id="orders">
            <div class="row form-group">
                <div>
                    <h3>Orders</h3>
                </div>
                <div class="row form-group"></div>
                    <div class="col-md-4">
                       <label for="product-name"> Name</label>
                       <input type="text" class="form-control" name="name">
                    </div>
                </div>
                <div class="row form">
                    <div class="col-md-4">
                        <label for="product-type">Type</label>
                        <input type="text" class="form-control" name="">
                    </div>
                </div>
                <div class="row form">
                    <div class="col-md-4">
                        <label for="orders-quantity">Quantity</label>
                        <input type="text" class="form-control" name="">
                    </div>                   
                </div>
                <div class="row form">
                    <div class="col-md-4">
                        <label for="price">Price</label>
                        <input type="number" class="form-control" name="">
                    </div>
                </div>
                <div class="row form">
                    <div class="col-md-4">
                        <label for="discount">Discount</label>
                        <input type="number" class="form-control" name="">
                </div>
            </div>
            <div class="row form">
                <div class="col-md-4">
                  <input type="submit" value="Submit" class="btn btn-primary">
                </div>
               </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

faithapp/faith1/templates/new_product.html
{% include 'base.html'%}
{% include 'navigation.html'%}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="col-lg-12">
        <form id="products">
            <div class="row form-group">
                <div><h3>Products</h3></div>
                <div class="row form">
                  <div class="col-md-4"> 
                     <label for="product-name">Product Name</label>
                     <input type="text" class="form-control" name="name">
                  </div>
                </div>
                <div class="row form">
                  <div class="col-md-4">
                    <label for="product-type"> Product Type</label>
                    <input type="text" class="form-control" name="type">
                  </div>
                </div>
                <div class="row form">
                  <div class="col-md-4">
                        <label for="quantity-per-unit">Quantity Per Unit</label>
                        <input type="number" class="form-control" name="">
                  </div>
                </div>
                <div class="row form">
                  <div class="col-md-4">
                        <label for="unit-price">Unit Price</label>
                        <input type="number" class="form-control" name="">
                  </div>
                  
                </div>
                <div class="row form">
                  <div class="col-md-4">
                        <label for="unit-in-stock">Unit in Stock</label>
                        <input type="number" class="form-control" name="">
                  </div>
                </div>
                <div class="row form">
                  <div class="col-md-4">
                        <label for="unit-on-order">Unit on Order</label>
                        <input type="number" class="form-control" name="">
                  </div>
                </div>
                <div class="row form">
                  <div class="col-md-4">
                        <label for="re-order-level">Re-oder Level</label>
                        <input type="number" class="form-control" name="">
                  </div>
                </div>
                <div class="row form">
                   <div class="col-md-4">
                      <input type="submit" value="submit" class="btn btn-primary">
                   </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

faithapp/faith1/templates/new_suppliers.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="col-lg-12">
        <form id="suppliers">
            <div><h3>Suppliers</h3></div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label for="id_name">Name</label>
                    <input type="text" class="form-control" id="id_name" name="name" required>
                </div>
                <div class="col-md-4">
                    <label for="id_phone_number">Phone Number</label>
                    <input type="number" class="form-control" id="id_phone_number" name="phone_number">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label for="id_items">Items</label>
                    <input type="text" class="form-control" id="id_items" name="items">
                </div>
                <div class="col-md-4">
                    <label for="id_home_page">Home page</label>
                    <input type="text" class="form-control" id="id_home_page" name="home_page">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label for="id_company_name">Company Name</label>
                    <input type="text" class="form-control" id="id_company_name" name="company_name">
                </div>
                <div class="col-md-4">
                    <label for="id_contact_name">Contact Name</label>
                    <input type="text" class="form-control" id="id_contact_name" name="contact_name">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label for="id_contact_title">Contact Title</label>
                    <input type="text" class="form-control" id="id_contact_title" name="contact_title">
                </div>
                <div class="col-md-4">
                    <label for="id_address">Address</label>
                    <input type="text" class="form-control" id="id_address" name="address">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label for="id_town">Town</label>
                    <input type="text" class="form-control" id="id_town" name="town">
                </div>
                <div class="col-md-4">
                    <label for="id_country">Country</label>
                    <input type="text" class="form-control" id="id_country" name="country">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4">
                    <label for="id_county">County</label>
                    <input type="text" class="form-control" id="id_county" name="county">
                </div>
                <div class="col-md-4">
                    <label for="id_postal_code">Postal Code</label>
                    <input type="number" class="form-control" id="id_postal_code" name="postal_code">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4">
                    <input type="submit" value="Submit" class="btn btn-primary">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}